### ISSUE TITLE
Add Android Sample (WebView)

### ISSUE THREAD

**Issue by 05nelsonm** [05nelsonm/kmp-tor#251]
Add a barebones sample Android project that starts Tor and overrides webview proxy.

See:
https://gist.github.com/05nelsonm/8bc3fa33272fc596219a16b0eb2d217f

**Comment by holywend** [comment]
any sample project?

**Comment by 05nelsonm** [comment]
Issue moved to [kmp-tor-samples](https://github.com/05nelsonm/kmp-tor-samples) repo
