### ISSUE TITLE
Library not working for some reason

### ISSUE THREAD

**Issue by michaelWuensch** [05nelsonm/kmp-tor#297]
Hi, I wanted to migrate from TOPL to your new kmp-tor on ZapAndroid.

For some reason Android Studio behaves as if the library is not available. It does not throw any error, but when using 
`import io.matthewnelson ...`
is not even available

I added the following under dependencies:
```
def vTor = '4.7.13-4'
def vKmpTor = '1.4.2'
implementation "io.matthewnelson.kotlin-components:kmp-tor:$vTor-$vKmpTor"
```
I followed the instructions on Android setup instructions in the kmp-tor-binary repo (I only ingored the splitting part)

As repository I added mavenCentral().

Any idea what might cause this?

**Comment by 05nelsonm** [comment]
No clue, it's there in maven repo.

![image](https://user-images.githubusercontent.com/44778092/229120610-922f31cd-ec0c-40e2-903f-d63da24799af.png)

Maybe:
 - Close AS
 - `./gradlew clean`
 - delete `.idea`
 - delete `.gradle/`
 - Open AS and re-import?

**Comment by michaelWuensch** [comment]
Thanks for your answer. Unfortunately it did not help. But I found this sync issue information:

Unresolved dependencies

The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.4.2'. However we cannot choose between the following variants of io.matthewnelson.kotlin-components:kmp-tor:4.7.13-4-1.4.2:
  - jvmApiElements-published
  - jvmRuntimeElements-published
  - releaseApiElements-published
  - releaseRuntimeElements-published
  - samplessources
All of them match the consumer attributes:
  - Variant 'jvmApiElements-published' capability io.matthewnelson.kotlin-components:kmp-tor:4.7.13-4-1.4.2 declares an API of a component:
      - Unmatched attributes:
          - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.4.2')
          - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Provides a library but the consumer didn't ask for it
          - Doesn't say anything about its target Java environment (preferred optimized for Android)
          - Provides its elements packaged as a jar but the consumer didn't ask for it
          - Provides release status but the consumer didn't ask for it
          - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but the consumer didn't ask for it
  - Variant 'jvmRuntimeElements-published' capability io.matthewnelson.kotlin-components:kmp-tor:4.7.13-4-1.4.2 declares a runtime of a component:
      - Unmatched attributes:
          - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.4.2')
          - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Provides a library but the consumer didn't ask for it
          - Doesn't say anything about its target Java environment (preferred optimized for Android)
          - Provides its elements packaged as a jar but the consumer didn't ask for it
          - Provides release status but the consumer didn't ask for it
          - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but the consumer didn't ask for it
  - Variant 'releaseApiElements-published' capability io.matthewnelson.kotlin-components:kmp-tor:4.7.13-4-1.4.2 declares an API of a component:
      - Unmatched attributes:
          - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.4.2')
          - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Provides a library but the consumer didn't ask for it
          - Doesn't say anything about its target Java environment (preferred optimized for Android)
          - Provides release status but the consumer didn't ask for it
          - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but the consumer didn't ask for it
  - Variant 'releaseRuntimeElements-published' capability io.matthewnelson.kotlin-components:kmp-tor:4.7.13-4-1.4.2 declares a runtime of a component:
      - Unmatched attributes:
          - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.4.2')
          - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Provides a library but the consumer didn't ask for it
          - Doesn't say anything about its target Java environment (preferred optimized for Android)
          - Provides release status but the consumer didn't ask for it
          - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but the consumer didn't ask for it
  - Variant 'samplessources' capability io.matthewnelson.kotlin-components:kmp-tor:4.7.13-4-1.4.2:
      - Unmatched attributes:
          - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.4.2')
          - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Provides documentation but the consumer didn't ask for it
          - Provides documentation of type 'samplessources' but the consumer didn't ask for it
          - Doesn't say anything about its target Java environment (preferred optimized for Android)
          - Provides release status but the consumer didn't ask for it
          - Doesn't say anything about its usage (required an API)
The following variants were also considered but didn't match the requested attributes:
  - Variant 'commonMainMetadataElements' capability io.matthewnelson.kotlin-components:kmp-tor:4.7.13-4-1.4.2:
      - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed an API of a component
      - Other compatible attributes:
          - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.4.2')
          - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Doesn't say anything about its target Java environment (preferred optimized for Android)
  - Variant 'metadataApiElements' capability io.matthewnelson.kotlin-components:kmp-tor:4.7.13-4-1.4.2:
      - Incompatible because this component declares a usage of 'kotlin-metadata' of a component and the consumer needed an API of a component
      - Other compatible attributes:
          - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.4.2')
          - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
          - Doesn't say anything about its target Java environment (preferred optimized for Android)

**Comment by 05nelsonm** [comment]
What's your version of Android Gradle Plugin, and the Java version being used for Android Studio. I know that if it's not set to 11+, these sort of errors occur.

**Comment by michaelWuensch** [comment]
Dropdown:
![image](https://user-images.githubusercontent.com/15313630/229151981-262781e7-714b-4040-a684-032ebc1582d4.png)


Compile options are set to:
```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
```

**Comment by 05nelsonm** [comment]
And specifying the `-android` variant gives the same error?

```kotlin
dependencies {
    implementation("io.matthewnelson.kotlin-componentns:kmp-tor-android:4.7.13-4-1.4.2")
}
```

**Comment by michaelWuensch** [comment]
No, this works kind of (the library is now shown und Project -> External libraries), but then causes 3 sync issue warnings, each one looking quite similar to what I posted above, but for:
io.matthewnelson.kotlin-components:kmp-tor-manager:1.4.2
io.matthewnelson.kotlin-components:kmp-tor-binary-geoip:4.7.13-4
io.matthewnelson.kotlin-components:kmp-tor-binary-extract:4.7.13-4

By the way this is the GradlePlugin version:
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip`

**Comment by michaelWuensch** [comment]
![image](https://user-images.githubusercontent.com/15313630/229157919-54ee8ada-ab73-4916-b62a-ae3e252879a6.png)

At least now all libraries are under project -> external libraries, so everything might work. 
Still on syncing the gradle plugin now throws 6 of these warnings mentioning the libraries that are actually there now. Maybe I try KGP or update gradle plugin later.

**Comment by 05nelsonm** [comment]
If you could also try importing an older version; I'm curious if something is up the `gradle-maven-publish` plugin when I last bumped it's version. Might not be appropriately packing `KotlinMetaData`

Can try
```
def vTor = '4.7.13-0'
def vKmpTor = '1.3.4'

implementation "io.matthewnelson.kotlin-components:kmp-tor:$vTor-$vKmpTor"
```

**Comment by 05nelsonm** [comment]
Yeah, you want the `-android` variants. Can you try adding that again to the `kmp-tor` dependency to see if things are ironed out?

**Comment by michaelWuensch** [comment]
Unfortunately it is not ironed out.
Adding -android results in a mix:
![image](https://user-images.githubusercontent.com/15313630/229165380-b0c8c685-24c7-4d7a-b427-6bc3101e1d2f.png)

Adding all subcomponents again with -android results still in -jvm stuff being added and then it even throws errors because of duplicate libraries.

**Comment by michaelWuensch** [comment]
I tried it with this version, too:
```
def vTor = '4.7.12-0'
def vKmpTor = '1.3.1'
```
behaved exactly the same with both gradle 7.5 & 8.0.2

Im an new to Kotlin, so I am not 100% sure what you mean with KGP. 
But I converted the following files:
settings.gradle -> settings.gradle.kts
build.gradle (project) -> build.gradle.kts
build.gradle (module) -> build.gradle.kts

I migrated everything from Groovy to Kotlin. Invalidated Caches, restarted, everything builds again... But exactly the same behavior (Tested for gradle plugin 7.5 & 8.0.2)

**Comment by 05nelsonm** [comment]
> I am not 100% sure what you mean with KGP

Kotlin Gradle Plugin. Add it to the root project buildscript classpath. Don't think you'll need to apply the plugin to the app project, but I'm not entirely certain.

What version of AGP? Might try updating that, too?

**Comment by michaelWuensch** [comment]
AGP version in all my tests was up to date (7.4.2)

Adding KGP fixed it :tada: 
It works fine now without having to add -android.
Furthermore I tested it the following two environments, both worked:
1. Gradle version 7.5, build files written in Groovy, KGP version 1.8.10
2. Gradle version 8.0.2, build files written in Kotlin, KGP version 1.8.10

It might make sense to add KGP as requirement in your docs, unless you are able to do it without KGP.
Thanks for your support.

**Comment by 05nelsonm** [comment]
Wonderful! Did you have to apply it to the `app` module, or only have it in your root project `buildscript`'s `classpath`?

Weird that that was it, as Java projects don't seem to need KGP: https://github.com/craigraw/kmp-tor-java

**Comment by michaelWuensch** [comment]
I just tested it, the Plugin also needs to be applied, just adding it in the classpath is not enough.

**Comment by 05nelsonm** [comment]
Very glad things are working in Zap!

I created #300 to update the documentation so that (hopefully) others won't run into the same issue.
