### ISSUE TITLE
Some feedback / struggeling without documentation

### ISSUE THREAD

**Issue by michaelWuensch** [05nelsonm/kmp-tor#298]
Hi, 
yesterday I started to implement it after it was finally building.
Connection is already working, so the basics were quite straight forward with your sample apps.

I went the route for callbacks for non-kotlin consumers.
As I can't find any documentation, the details get confusing though or seem over complicated some times. Or maybe I am just doing it wrong. :) 

Here is some feedback / some issues I currently encounter:

**It always starts tor automatically**
```
// Instantiate new TorManager
TorManager manager = TorManager.newInstance(App.getAppContext(), loader);
```
I didn't find a way to just prepare the tor manager and then later call .start() when I actually need it.
This can be circumvented easily manually of course by keeping track if it was already started etc, but I wonder why it is not supported in the library directly.

**TorListener**
I can get this to work fine on initial Tor connection (like in the sample app).
But as soon as I try to stop and start the CallbackTorManager no events are triggered anymore.
Note that I used .startQuietly() & .stopQuietly(). Maybe that is the reason. But why isn't there a way to just do a stop, start & restart with the TorListener working without needing to provide anything?

**DefaultSettings**
I went with the TorConfigProviderAndroid settings you used in your Java Android App sample for now. (https://github.com/05nelsonm/kmp-tor/blob/master/samples/java/android/src/main/java/io/matthewnelson/kmp/tor/sample/java/android/App.java)
It works, but I can also see, that the settings in your kotlin sample app for Android are different. (https://github.com/05nelsonm/kmp-tor/blob/master/samples/kotlin/android/src/main/java/io/matthewnelson/kmp/tor/sample/kotlin/android/SampleApp.kt)
For none Tor experts it is hard to decide what to use, especially if there is no documentation yet.

**Comment by 05nelsonm** [comment]
Love it! Yeah there are some pain points and documentation that is needed which I hope to resolve with `2.0.0`. But... It works :partying_face: , lol.

> It always starts tor automatically
> ```
> // Instantiate new TorManager
> TorManager manager = TorManager.newInstance(App.getAppContext(), loader);
> ```

This should **not** be the case. Instantiating `TorManager` (and then wrapping in `CallbackTorManager`) should do nothing but create the instance(s). The APIs are such that you must call `start()` or `startQuietly()`. If tor is already started, those calls do nothing.

> I didn't find a way to just prepare the tor manager and then later call .start() when I actually need it. This can be circumvented easily manually of course by keeping track if it was already started etc, but I wonder why it > is not supported in the library directly.

`TorManager` and `CallbackTorManager` both implement [TorStateManager](https://github.com/05nelsonm/kmp-tor/blob/master/library/manager/kmp-tor-manager-common/src/commonMain/kotlin/io/matthewnelson/kmp/tor/manager/common/state/TorStateManager.kt). So no need to keep track, it does that for you!

> But as soon as I try to stop and start the CallbackTorManager no events are triggered anymore.
Note that I used .startQuietly() & .stopQuietly(). Maybe that is the reason. 

All events are dispatched to all attached listeners. `CallbackTorManager` is simply a wrapper which passes through everything to its delegate, `TorManager`. So, I'm not entirely sure what is happening here as integration tests indicate this is the case. Calling `startQuietly()` or `stopQuietly()` operate the same as `start()` and `stop()` but w/o the responses.

> But why isn't there a way to just do a stop, start & restart with the TorListener working without needing to provide anything?

Could you elaborate? Not sure what is needed to be provided as `start`, `stop`, `restart` take nothing as arguments for `TorManager` as they are suspend functions, while taking callbacks (for `CallbackTorManager`). If you do not want to wait for tor to start/stop/restart via `suspend` function (or conversely by providing callbacks, the `*Quietly` functions are there for that.

> For none Tor experts it is hard to decide what to use, especially if there is no documentation yet.

Agreed! Definitely need to achieve parity between those samples. I created #299 for this!
