### ISSUE TITLE
Android sample parity

### ISSUE THREAD

**Issue by 05nelsonm** [05nelsonm/kmp-tor#299]
There's some differences between the `kotlin` and `java` sample app configurations for Android. They should be brought into parity. need to copy/pasta some things so that they are the exact same so it is less confusing to consumers trying to implement `kmp-tor`.

**Comment by KoalaSat** [comment]
Hey @05nelsonm I think I can take care of this, any preference of which one is the right implementation or were you thinking on a good mix?

**Comment by 05nelsonm** [comment]
> Hey @05nelsonm I think I can take care of this, any preference of which one is the right implementation or were you thinking on a good mix?

Wouldn't worry about it right now.

With 2.0.0 coming in the next week or 2, current samples will be obseleted. A separate repository will be where samples live, `kmp-tor-samples`.

Thanks for the offer though!

**Comment by KoalaSat** [comment]
> > Hey @05nelsonm I think I can take care of this, any preference of which one is the right implementation or were you thinking on a good mix?
> 
> Wouldn't worry about it right now.
> 
> With 2.0.0 coming in the next week or 2, current samples will be obseleted. A separate repository will be where samples live, `kmp-tor-samples`.
> 
> Thanks for the offer though!

Okay good to know, I'm really looking forward for 2.0.0 so if there any way I can contribute to this project please let me know, it brings me a lot of value 🙂
