### ISSUE TITLE
v2.0 Status

### ISSUE THREAD

**Issue by michaelWuensch** [05nelsonm/kmp-tor#544]
Hello there,
what is the status of the v2.0 refactoring. The milestone is at 99% since 3 months now. Is there any estimate when a new version will actually be released?

I am asking because of the following reason.
I implemented the old TOPL library in BitBanana and it worked quite well. But increasing the API above 33 causes the app to crash as soon as tor is used. Therefore I wanted to upgrade to its new successor kmp-tor.
I now see that kmp-tor 1.0 is outdated as well and undergoes a major refactoring.
So if kmp-tor 2.0 will happen anytime soon, I'd rather wait and implement that than implementing another outdated library.
The annoying thing is, I can no longer make releases on PlayStore as it requires API of 34 or higher.

**Comment by 05nelsonm** [comment]
`2.0.0-alpha01` is now available. Far better tested and fleshed out API. You'd be OK to use it in prod as I do not foresee anything changing between now and `2.0.0` (famous last words). If there are any changes needed to the API, they'll be very minor.

**Comment by michaelWuensch** [comment]
Thank you so much!
In the coming days I'll first try the fix to get topl library working so I can make releases again. And after that start to migrate to the kmp tor without pressure.

**Comment by michaelWuensch** [comment]
@05nelsonm I just tried your solution from above. It did not work for the TOPL library. It throws this error:

java.lang.SecurityException: app.michaelwuensch.bitbanana.debug: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

probably could be fixed in TorServiceReceiver.kt line 141.
I guess I'll have to go through migrating to the new kmp library then.

**Comment by michaelWuensch** [comment]
@05nelsonm got it working with 2.0.0-alpha02
