### ISSUE TITLE
[Suggestion] Sample Addition

### ISSUE THREAD

**Issue by ShiroBlank** [05nelsonm/kmp-tor#70]
Hey, I'm pretty new in the whole kotlin space so forgive me if this is redundant, but, as far as I'm aware javaFX isn't embedded in the JRE by default anymore, making it an additional dependency users have too install.

Saying that would it be possible for you too supply a sample that doesn't utilize javafx, maybe just a pure console application or something as this is what the application I'm working on is based around.

Awaiting your response, sorry for my bad English.

--Shiro

**Comment by 05nelsonm** [comment]
The javafx sample uses the gradle plugin, which I thought was a work-around for that.

I am able to run it on MacOS, Windows, and Linux just fine using terminal (Unix)/cmd prompt (Windows) via

```
./gradlew :samples:javafx:run
```

As documented in the README.md

Is that not working for you?

**Comment by 05nelsonm** [comment]
Ah. you may be experiencing some Kotlin Multiplatform dependency issues related to Android, and/or other platform targets (windows, macos) that might require you to install dependencies.

You can pass a property in the terminal command when running the javafx sample to build and run only the JVM components

```
./gradlew :samples:javafx:run -PKMP_TARGETS=JVM
```

Additionally, you can add the property target globally by adding to your `~/.gradle/gradle.properties` file the following

```
KMP_TARGETS=JVM
### Additional KMP Targets
# ANDROID
# LINUX_ARM32HFP,LINUX_MIPS32,LINUX_MIPSEL32,LINUX_X64
# IOS_ALL,IOS_ARM32,IOS_ARM64,IOS_X64,MACOS_ARM64,MACOS_X64,TVOS_ALL,TVOS_ARM64,TVOS_X64,WATCHOS_ALL,WATCHOS_ARM32,WATCHOS_ARM64,WATCHOS_X64,WATCHOS_X86,IOS_SIMULATOR_ARM64,TVOS_SIMULATOR_ARM64,WATCHOS_SIMULATOR_ARM64
# MINGW_X64,MINGW_X86
```

See [HERE](https://github.com/05nelsonm/kotlin-components/blob/13d6f987ef5676718e881758637330ac88a1b9b7/includeBuild/kmp/src/main/kotlin/io/matthewnelson/kotlin/components/kmp/KmpConfigurationPlugin.kt#L156) for more info about target expression

**Comment by ShiroBlank** [comment]
Hello, excuse my incompetence as I had issues making the example project working. I will now try to make it functional and attempt what you have written. 

Thank you for your help.

--Shiro

**Comment by ShiroBlank** [comment]
I have tried what you commented and the example application is now running and building, the key was `./gradlew :samples:javafx:run -PKMP_TARGETS=JVM` Thank you for your help, and as you explained in your first comment, the javafx in maven bypasses the additional dependency issue.

Thanks for your help, amazing project. 

--Shiro
